FROM debian:jessie-slim

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y texlive-xetex && \
    rm -rf /var/lib/apt/lists/

RUN apt-get update -y && \
    apt-get install -y build-essential curl && \
    rm -rf /var/lib/apt/lists

WORKDIR /papers

ENV CARGO_HOME /papers/.cargo
ENV PATH=/papers/.cargo/bin:$PATH

RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
RUN rustup default stable

COPY . .

CMD cargo test
